import { Express } from "express";
import auth from "./auth";
import chatCommandsRouter from "./chatCommands";
import configsRouter from "./configs";
import messagesRouter from "./messages";
import redemptionsRouter from "./redemptions";
import triggersRouter from "./triggers";
import timersRouter from "./timers";
import usersRouter from "./users";
import streamSessionsRouter from "./streamSessions";
import messageCategoriesRouter from "./messageCategories";
import overlayRouter from "./overlays";
import widgetsRouter from "./widgets";
import moodsRouter from "./moods";
import tagsRouter from "./tags";
import affixesRouter from "./affixes";
import filesRouter from "./files";
import songsRouter from "./songs";
import achievementsRouter from "./achievements";
import youtubeRouter from "./youtube";

export const initRoutes = (app: Express) => {
  app.use("/achievements", achievementsRouter);
  app.use("/auth", auth);
  app.use("/chat-commands", chatCommandsRouter);
  app.use("/configs", configsRouter);
  app.use("/messages", messagesRouter);
  app.use("/message-categories", messageCategoriesRouter);
  app.use("/moods", moodsRouter);
  app.use("/overlays", overlayRouter);
  app.use("/users", usersRouter);
  app.use("/affixes", affixesRouter);
  app.use("/redemptions", redemptionsRouter);
  app.use("/stream-sessions", streamSessionsRouter);
  app.use("/tags", tagsRouter);
  app.use("/triggers", triggersRouter);
  app.use("/timers", timersRouter);
  app.use("/songs", songsRouter);
  app.use("/files", filesRouter);
  app.use("/widgets", widgetsRouter);
  app.use("/youtube", youtubeRouter);
};
