export enum BaseEndpointNames {
  ACHIEVEMENTS = "achievements",
  BADGES = "badges",
  STAGES = "stages",
  AUTH = "auth",
  AFFIXES = "affixes",
  CHAT_COMMANDS = "chat-commands",
  CONFIGS = "configs",
  FILES = "files",
  MESSAGE_CATEGORIES = "message-categories",
  MESSAGES = "messages",
  MOODS = "moods",
  OVERLAYS = "overlays",
  SONGS = "songs",
  STREAM_SESSIONS = "stream-sessions",
  TAGS = "tags",
  TIMERS = "timers",
  TRIGGERS = "triggers",
  USERS = "users",
  REDEMPTIONS = "redemptions",
  WIDGETS = "widgets",
}
