export enum CustomAchievementAction {
  ALL = "ALL MESSAGES",
  INCLUDES = "INCLUDES",
  STARTS_WITH = "STARTS WITH",
  ENDS_WITH = "ENDS WITH",
  MESSAGE_GT = "MESSAGE LENGTH GREATER THAN",
  MESSAGE_LT = "MESSAGE LENGTH LESS THAN",
  WATCH_TIME = "WATCH TIME"
}
