import ReactGridLayout from "react-grid-layout";

const defaultsLayoutOpts = {
  isDraggable: false,
  isResizable: false,
  static: false,
};

export const initialLayoutWidgets: ReactGridLayout.Layouts = {
  ulg: [
    { i: "stream-chat", x: 0, y: 0, w: 15, h: 60, ...defaultsLayoutOpts },
    { i: "stream-chatters", x: 15, y: 0, w: 10, h: 25, ...defaultsLayoutOpts },
    {
      i: "stream-notifications",
      x: 75,
      y: 0,
      w: 25,
      h: 25,
      ...defaultsLayoutOpts,
    },
    {
      i: "stream-statistics",
      x: 15,
      y: 25,
      w: 85,
      h: 35,
      ...defaultsLayoutOpts,
    },
    { i: "messages-window", x: 25, y: 0, w: 10, h: 25, ...defaultsLayoutOpts },
    { i: "rewards-window", x: 62, y: 0, w: 14, h: 25, ...defaultsLayoutOpts },

    { i: "stream-modes", x: 35, y: 0, w: 15, h: 25, ...defaultsLayoutOpts },
    { i: "music-player", x: 50, y: 0, w: 12, h: 25, ...defaultsLayoutOpts },
  ],
  lg: [
    { i: "stream-chat", x: 0, y: 0, w: 20, h: 25, ...defaultsLayoutOpts },
    { i: "stream-chatters", x: 20, y: 0, w: 15, h: 25, ...defaultsLayoutOpts },
    {
      i: "stream-notifications",
      x: 70,
      y: 0,
      w: 30,
      h: 25,
      ...defaultsLayoutOpts,
    },
    {
      i: "stream-statistics",
      x: 20,
      y: 25,
      w: 60,
      h: 30,
      ...defaultsLayoutOpts,
    },
    { i: "messages-window", x: 35, y: 0, w: 15, h: 25, ...defaultsLayoutOpts },
    { i: "rewards-window", x: 80, y: 25, w: 20, h: 30, ...defaultsLayoutOpts },
    { i: "stream-modes", x: 50, y: 0, w: 20, h: 25, ...defaultsLayoutOpts },
    { i: "music-player", x: 0, y: 25, w: 20, h: 30, ...defaultsLayoutOpts },
  ],
  md: [
    { i: "stream-chat", x: 0, y: 0, w: 15, h: 30, ...defaultsLayoutOpts },
    { i: "stream-chatters", x: 15, y: 15, w: 15, h: 15, ...defaultsLayoutOpts },
    {
      i: "stream-notifications",
      x: 60,
      y: 0,
      w: 25,
      h: 30,
      ...defaultsLayoutOpts,
    },
    {
      i: "stream-statistics",
      x: 0,
      y: 30,
      w: 60,
      h: 22,
      ...defaultsLayoutOpts,
    },
    { i: "messages-window", x: 15, y: 0, w: 15, h: 15, ...defaultsLayoutOpts },
    { i: "rewards-window", x: 60, y: 30, w: 20, h: 22, ...defaultsLayoutOpts },
    { i: "stream-modes", x: 30, y: 0, w: 25, h: 15, ...defaultsLayoutOpts },
    { i: "music-player", x: 30, y: 15, w: 25, h: 15, ...defaultsLayoutOpts },
  ],
  sm: [
    { i: "stream-chat", x: 0, y: 0, w: 15, h: 40, ...defaultsLayoutOpts },
    { i: "stream-chatters", x: 15, y: 25, w: 15, h: 15, ...defaultsLayoutOpts },
    {
      i: "stream-notifications",
      x: 30,
      y: 0,
      w: 30,
      h: 15,
      ...defaultsLayoutOpts,
    },
    {
      i: "stream-statistics",
      x: 0,
      y: 40,
      w: 40,
      h: 30,
      ...defaultsLayoutOpts,
    },
    { i: "messages-window", x: 15, y: 0, w: 15, h: 25, ...defaultsLayoutOpts },
    { i: "rewards-window", x: 60, y: 40, w: 20, h: 30, ...defaultsLayoutOpts },
    { i: "stream-modes", x: 45, y: 15, w: 15, h: 25, ...defaultsLayoutOpts },
    { i: "music-player", x: 30, y: 15, w: 15, h: 25, ...defaultsLayoutOpts },
  ],
  xs: [
    { i: "stream-chat", x: 0, y: 0, w: 10, h: 20, ...defaultsLayoutOpts },
    { i: "stream-chatters", x: 10, y: 10, w: 10, h: 10, ...defaultsLayoutOpts },
    {
      i: "stream-notifications",
      x: 28,
      y: 0,
      w: 12,
      h: 20,
      ...defaultsLayoutOpts,
    },
    {
      i: "stream-statistics",
      x: 10,
      y: 20,
      w: 30,
      h: 25,
      ...defaultsLayoutOpts,
    },
    { i: "messages-window", x: 10, y: 0, w: 10, h: 10, ...defaultsLayoutOpts },
    { i: "rewards-window", x: 0, y: 35, w: 10, h: 15, ...defaultsLayoutOpts },
    { i: "stream-modes", x: 20, y: 0, w: 8, h: 20, ...defaultsLayoutOpts },
    { i: "music-player", x: 0, y: 20, w: 10, h: 15, ...defaultsLayoutOpts },
  ],
  xxs: [
    { i: "stream-chat", x: 0, y: 0, w: 10, h: 15, ...defaultsLayoutOpts },
    { i: "stream-chatters", x: 10, y: 8, w: 10, h: 7, ...defaultsLayoutOpts },
    {
      i: "stream-notifications",
      x: 15,
      y: 30,
      w: 10,
      h: 25,
      ...defaultsLayoutOpts,
    },
    {
      i: "stream-statistics",
      x: 0,
      y: 30,
      w: 10,
      h: 5,
      ...defaultsLayoutOpts,
    },
    { i: "messages-window", x: 10, y: 0, w: 10, h: 8, ...defaultsLayoutOpts },
    { i: "rewards-window", x: 0, y: 35, w: 10, h: 15, ...defaultsLayoutOpts },
    { i: "stream-modes", x: 0, y: 15, w: 10, h: 15, ...defaultsLayoutOpts },
    { i: "music-player", x: 15, y: 15, w: 10, h: 15, ...defaultsLayoutOpts },
  ],
};

export const initialToolboxWidgets: ReactGridLayout.Layouts = {
  ulg: [],
  lg: [],
  md: [],
  sm: [],
  xs: [],
  xxs: [],
};
