export enum ACHIEVEMENTS {
  WATCH_TIME = "WATCH TIME",
  CHAT_MESSAGES = "CHAT MESSAGES",
  POINTS = "POINTS",
  FOLLOWAGE = "FOLLOWER",
  COMMANDS_COUNT = "COMMANDS",
  SONG_REQUEST = "MY MUSIC",
  SONG_VOTING = "MY MUSIC TASTE",
  BADGES_COUNT = "OBTAINED BADGES"
}
