export enum ACHIEVEMENTS {
  WATCH_TIME = "WATCH TIME",
  CHAT_MESSAGES = "CHAT MESSAGES",
  DOTS = "DOT COUNTS",
  QUESTION_MARKS = "QUESTION MARKS",
  COMMAS = "COMMA COMMA",
  DICTATOR = "DICTATOR",
  MONKEY = "MONKEY",
  LONG_MESSAGES = "WORD SMITH",
  SHORT_MESSAGES = "ENTER",
  XD = "XD",
  POLISH_SWEARING = "MIENSO",
  KAPPA = "KAPPA",
  LUL = "LUL",
  COMMANDS_COUNT = "COMMANDS",
  SONG_REQUEST = "MY MUSIC",
  SONG_VOTING = "MY MUSIC TASTE"
}

//sorry for swearing LUL
export enum POLISH_SWEARING {
  KURWA = "kurwa",
  PIERDOLE = "pierdole",
  CHUJ = "chuj",
  PIZDA = "pizda",
  JEBAC = "jebac",
  JEBAC2 = "jebać"
}
